num1 = int(input("Enter your number: "))
num2 = int(input("Enter your number: "))
num3 = int(input("Enter your number: "))
num4 = int(input("Enter your number: "))
num5 = int(input("Enter your number: "))
num6 = int(input("Enter your number: "))
num7 = int(input("Enter your number: "))
num8 = int(input("Enter your number: "))
s = {num1, num2, num3, num4, num5, num6, num7, num8}
print(s)